[package]
name = "zub"
version = "0.2.0"
edition = "2021"

[lib]
name = "zub"
path = "src/lib.rs"

[[bin]]
name = "zub"
path = "src/main.rs"

[[bin]]
name = "zub-scaffold"
path = "src/bin/zub-scaffold.rs"

[dependencies]
serde = { version = "1", features = ["derive"] }
yaml_serde = "0.10"
terminal_size = "0.4"
lexopt = "0.3"

[dev-dependencies]
tempfile = "3"
