#!/usr/bin/env bash
#@ summary: Show who is logged in
#@ usage: $0 [opts...]
#@ help: |
#@   Example command generated by zub-scaffold. It forwards all of its
#@   arguments to the system `who` command.
#@
#@   It also demonstrates the two things a completion-capable command needs:
#@   a `complete: true` front-matter flag, and a `--complete` branch that
#@   prints candidate words (one per line) for the argument being typed.
#@ complete: true

set -e

# When zub drives completion it runs this script as `@NAME@ who --complete ...`.
# Print one candidate per line for the word currently being completed; the
# word itself is available in $COMP_LASTARG.
if [ "$1" = "--complete" ]; then
  printf '%s\n' -a -b -H -q -u
  exit 0
fi

exec who "$@"
